"""Auto-generated impact validation tests.

Generated by Impact Radar V2 DynamicTestGenerator.
These tests validate structural relationships in the curated dependency graph.
Every assertion is grounded in the bipartite graph — no hallucinated data.
"""

import pytest
from pathlib import Path

from src.graph.builder import DependencyGraph
from src.graph.traverser import ImpactTraverser


DATA_DIR = Path(__file__).parent.parent / "data"
COMPONENTS_DIR = DATA_DIR / "components"
VARIANTS_DIR = DATA_DIR / "variants"


@pytest.fixture
def graph() -> DependencyGraph:
    """Load the curated dependency graph."""
    return DependencyGraph(COMPONENTS_DIR, VARIANTS_DIR)


@pytest.fixture
def traverser(graph) -> ImpactTraverser:
    """Create a traverser with default settings."""
    return ImpactTraverser(graph)


# Verify all expected components exist in the graph
# Grounding: Graph contains 12 components
def test_all_components_present(graph):
    """All curated components must be present in the loaded graph."""
    expected = ['api_gateway', 'audit_logger', 'auth_engine', 'billing_core', 'data_exporter', 'encryption_service', 'notification_service', 'pricing_engine', 'report_generator', 'search_service', 'websocket_gateway', 'workflow_engine']
    actual = sorted(graph.get_components().keys())
    assert actual == expected


# Verify graph has exactly 12 components
# Grounding: Graph summary shows 12 components
def test_component_count(graph):
    """Component count must match the curated graph."""
    assert graph.summary()["component_count"] == 12


# Changing api_gateway should directly impact peers via access_control
# Grounding: Module 'access_control' is shared by: api_gateway, auth_engine, workflow_engine
def test_direct_impact_via_access_control(graph, traverser):
    """Components sharing 'access_control' must appear as direct impacts."""
    result = traverser.traverse(["api_gateway"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['auth_engine', 'workflow_engine']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of api_gateway via access_control"
        )


# Changing api_gateway should directly impact peers via cache_layer
# Grounding: Module 'cache_layer' is shared by: api_gateway, billing_core, search_service
def test_direct_impact_via_cache_layer(graph, traverser):
    """Components sharing 'cache_layer' must appear as direct impacts."""
    result = traverser.traverse(["api_gateway"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['billing_core', 'search_service']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of api_gateway via cache_layer"
        )


# Changing api_gateway should directly impact peers via config_loader
# Grounding: Module 'config_loader' is shared by: api_gateway, billing_core, encryption_service
def test_direct_impact_via_config_loader(graph, traverser):
    """Components sharing 'config_loader' must appear as direct impacts."""
    result = traverser.traverse(["api_gateway"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['billing_core', 'encryption_service']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of api_gateway via config_loader"
        )


# Changing auth_engine should directly impact peers via crypto_utils
# Grounding: Module 'crypto_utils' is shared by: auth_engine, encryption_service
def test_direct_impact_via_crypto_utils(graph, traverser):
    """Components sharing 'crypto_utils' must appear as direct impacts."""
    result = traverser.traverse(["auth_engine"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['encryption_service']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of auth_engine via crypto_utils"
        )


# Changing billing_core should directly impact peers via currency_utils
# Grounding: Module 'currency_utils' is shared by: billing_core, pricing_engine, report_generator
def test_direct_impact_via_currency_utils(graph, traverser):
    """Components sharing 'currency_utils' must appear as direct impacts."""
    result = traverser.traverse(["billing_core"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['pricing_engine', 'report_generator']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of billing_core via currency_utils"
        )


# Changing audit_logger should directly impact peers via db_connector
# Grounding: Module 'db_connector' is shared by: audit_logger, billing_core, report_generator, search_service
def test_direct_impact_via_db_connector(graph, traverser):
    """Components sharing 'db_connector' must appear as direct impacts."""
    result = traverser.traverse(["audit_logger"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['billing_core', 'report_generator', 'search_service']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of audit_logger via db_connector"
        )


# Changing audit_logger should directly impact peers via event_bus
# Grounding: Module 'event_bus' is shared by: audit_logger, auth_engine, notification_service, workflow_engine
def test_direct_impact_via_event_bus(graph, traverser):
    """Components sharing 'event_bus' must appear as direct impacts."""
    result = traverser.traverse(["audit_logger"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['auth_engine', 'notification_service', 'workflow_engine']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of audit_logger via event_bus"
        )


# Changing data_exporter should directly impact peers via file_storage
# Grounding: Module 'file_storage' is shared by: data_exporter, notification_service, report_generator
def test_direct_impact_via_file_storage(graph, traverser):
    """Components sharing 'file_storage' must appear as direct impacts."""
    result = traverser.traverse(["data_exporter"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['notification_service', 'report_generator']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of data_exporter via file_storage"
        )


# Changing notification_service should directly impact peers via i18n_utils
# Grounding: Module 'i18n_utils' is shared by: notification_service, report_generator, search_service
def test_direct_impact_via_i18n_utils(graph, traverser):
    """Components sharing 'i18n_utils' must appear as direct impacts."""
    result = traverser.traverse(["notification_service"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['report_generator', 'search_service']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of notification_service via i18n_utils"
        )


# Changing data_exporter should directly impact peers via job_scheduler
# Grounding: Module 'job_scheduler' is shared by: data_exporter, report_generator, workflow_engine
def test_direct_impact_via_job_scheduler(graph, traverser):
    """Components sharing 'job_scheduler' must appear as direct impacts."""
    result = traverser.traverse(["data_exporter"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['report_generator', 'workflow_engine']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of data_exporter via job_scheduler"
        )


# Changing data_exporter should directly impact peers via key_rotation
# Grounding: Module 'key_rotation' is shared by: data_exporter, encryption_service
def test_direct_impact_via_key_rotation(graph, traverser):
    """Components sharing 'key_rotation' must appear as direct impacts."""
    result = traverser.traverse(["data_exporter"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['encryption_service']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of data_exporter via key_rotation"
        )


# Changing api_gateway should directly impact peers via metrics_collector
# Grounding: Module 'metrics_collector' is shared by: api_gateway, billing_core, search_service, websocket_gateway
def test_direct_impact_via_metrics_collector(graph, traverser):
    """Components sharing 'metrics_collector' must appear as direct impacts."""
    result = traverser.traverse(["api_gateway"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['billing_core', 'search_service', 'websocket_gateway']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of api_gateway via metrics_collector"
        )


# Changing audit_logger should directly impact peers via query_builder
# Grounding: Module 'query_builder' is shared by: audit_logger, report_generator, search_service
def test_direct_impact_via_query_builder(graph, traverser):
    """Components sharing 'query_builder' must appear as direct impacts."""
    result = traverser.traverse(["audit_logger"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['report_generator', 'search_service']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of audit_logger via query_builder"
        )


# Changing api_gateway should directly impact peers via rate_limiter
# Grounding: Module 'rate_limiter' is shared by: api_gateway, pricing_engine, search_service
def test_direct_impact_via_rate_limiter(graph, traverser):
    """Components sharing 'rate_limiter' must appear as direct impacts."""
    result = traverser.traverse(["api_gateway"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['pricing_engine', 'search_service']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of api_gateway via rate_limiter"
        )


# Changing data_exporter should directly impact peers via retry_handler
# Grounding: Module 'retry_handler' is shared by: data_exporter, notification_service, websocket_gateway
def test_direct_impact_via_retry_handler(graph, traverser):
    """Components sharing 'retry_handler' must appear as direct impacts."""
    result = traverser.traverse(["data_exporter"])
    direct_ids = sorted(result.direct_impacts.keys())
    expected = ['notification_service', 'websocket_gateway']
    for comp_id in expected:
        assert comp_id in direct_ids, (
            f"{comp_id} should be a direct impact of data_exporter via retry_handler"
        )


# api_gateway indirectly impacts report_generator at depth 2
# Grounding: BFS traversal from api_gateway reaches report_generator at depth 2
def test_indirect_impact_api_gateway_to_report_generator(graph, traverser):
    """Traversal from api_gateway must reach report_generator indirectly."""
    result = traverser.traverse(["api_gateway"])
    all_affected = result.all_affected_components
    assert "report_generator" in all_affected, (
        "report_generator should be affected by changes to api_gateway"
    )
    # Must be indirect (depth > 1), not direct
    assert "report_generator" in result.indirect_impacts


# audit_logger indirectly impacts encryption_service at depth 2
# Grounding: BFS traversal from audit_logger reaches encryption_service at depth 2
def test_indirect_impact_audit_logger_to_encryption_service(graph, traverser):
    """Traversal from audit_logger must reach encryption_service indirectly."""
    result = traverser.traverse(["audit_logger"])
    all_affected = result.all_affected_components
    assert "encryption_service" in all_affected, (
        "encryption_service should be affected by changes to audit_logger"
    )
    # Must be indirect (depth > 1), not direct
    assert "encryption_service" in result.indirect_impacts


# auth_engine indirectly impacts data_exporter at depth 2
# Grounding: BFS traversal from auth_engine reaches data_exporter at depth 2
def test_indirect_impact_auth_engine_to_data_exporter(graph, traverser):
    """Traversal from auth_engine must reach data_exporter indirectly."""
    result = traverser.traverse(["auth_engine"])
    all_affected = result.all_affected_components
    assert "data_exporter" in all_affected, (
        "data_exporter should be affected by changes to auth_engine"
    )
    # Must be indirect (depth > 1), not direct
    assert "data_exporter" in result.indirect_impacts


# billing_core indirectly impacts notification_service at depth 2
# Grounding: BFS traversal from billing_core reaches notification_service at depth 2
def test_indirect_impact_billing_core_to_notification_service(graph, traverser):
    """Traversal from billing_core must reach notification_service indirectly."""
    result = traverser.traverse(["billing_core"])
    all_affected = result.all_affected_components
    assert "notification_service" in all_affected, (
        "notification_service should be affected by changes to billing_core"
    )
    # Must be indirect (depth > 1), not direct
    assert "notification_service" in result.indirect_impacts


# data_exporter indirectly impacts auth_engine at depth 2
# Grounding: BFS traversal from data_exporter reaches auth_engine at depth 2
def test_indirect_impact_data_exporter_to_auth_engine(graph, traverser):
    """Traversal from data_exporter must reach auth_engine indirectly."""
    result = traverser.traverse(["data_exporter"])
    all_affected = result.all_affected_components
    assert "auth_engine" in all_affected, (
        "auth_engine should be affected by changes to data_exporter"
    )
    # Must be indirect (depth > 1), not direct
    assert "auth_engine" in result.indirect_impacts


# Variant Enterprise APAC must contain its assigned components
# Grounding: Variant 'enterprise_apac' includes: api_gateway, audit_logger, auth_engine, billing_core, data_exporter, encryption_service, notification_service, pricing_engine, report_generator, search_service, websocket_gateway, workflow_engine
def test_variant_enterprise_apac_components(graph):
    """Variant 'Enterprise APAC' must have correct components."""
    variant = graph.get_variant("enterprise_apac")
    assert variant is not None, "Variant enterprise_apac must exist"
    comp_ids = sorted(c["component_id"] for c in variant.components)
    assert comp_ids == ['api_gateway', 'audit_logger', 'auth_engine', 'billing_core', 'data_exporter', 'encryption_service', 'notification_service', 'pricing_engine', 'report_generator', 'search_service', 'websocket_gateway', 'workflow_engine']


# Variant Enterprise EU must contain its assigned components
# Grounding: Variant 'enterprise_eu' includes: api_gateway, audit_logger, auth_engine, billing_core, data_exporter, encryption_service, notification_service, pricing_engine, report_generator, search_service, websocket_gateway, workflow_engine
def test_variant_enterprise_eu_components(graph):
    """Variant 'Enterprise EU' must have correct components."""
    variant = graph.get_variant("enterprise_eu")
    assert variant is not None, "Variant enterprise_eu must exist"
    comp_ids = sorted(c["component_id"] for c in variant.components)
    assert comp_ids == ['api_gateway', 'audit_logger', 'auth_engine', 'billing_core', 'data_exporter', 'encryption_service', 'notification_service', 'pricing_engine', 'report_generator', 'search_service', 'websocket_gateway', 'workflow_engine']


# Variant Enterprise must contain its assigned components
# Grounding: Variant 'enterprise_global' includes: api_gateway, audit_logger, auth_engine, billing_core, data_exporter, encryption_service, notification_service, pricing_engine, report_generator, search_service, websocket_gateway, workflow_engine
def test_variant_enterprise_global_components(graph):
    """Variant 'Enterprise' must have correct components."""
    variant = graph.get_variant("enterprise_global")
    assert variant is not None, "Variant enterprise_global must exist"
    comp_ids = sorted(c["component_id"] for c in variant.components)
    assert comp_ids == ['api_gateway', 'audit_logger', 'auth_engine', 'billing_core', 'data_exporter', 'encryption_service', 'notification_service', 'pricing_engine', 'report_generator', 'search_service', 'websocket_gateway', 'workflow_engine']


# Variant Platform must contain its assigned components
# Grounding: Variant 'platform_global' includes: api_gateway, auth_engine, billing_core, data_exporter, encryption_service, pricing_engine
def test_variant_platform_global_components(graph):
    """Variant 'Platform' must have correct components."""
    variant = graph.get_variant("platform_global")
    assert variant is not None, "Variant platform_global must exist"
    comp_ids = sorted(c["component_id"] for c in variant.components)
    assert comp_ids == ['api_gateway', 'auth_engine', 'billing_core', 'data_exporter', 'encryption_service', 'pricing_engine']


# Variant Professional EU must contain its assigned components
# Grounding: Variant 'professional_eu' includes: api_gateway, audit_logger, auth_engine, billing_core, encryption_service, notification_service, pricing_engine, report_generator, search_service, workflow_engine
def test_variant_professional_eu_components(graph):
    """Variant 'Professional EU' must have correct components."""
    variant = graph.get_variant("professional_eu")
    assert variant is not None, "Variant professional_eu must exist"
    comp_ids = sorted(c["component_id"] for c in variant.components)
    assert comp_ids == ['api_gateway', 'audit_logger', 'auth_engine', 'billing_core', 'encryption_service', 'notification_service', 'pricing_engine', 'report_generator', 'search_service', 'workflow_engine']


# Variant Professional must contain its assigned components
# Grounding: Variant 'professional_global' includes: api_gateway, auth_engine, billing_core, notification_service, pricing_engine, report_generator, search_service, workflow_engine
def test_variant_professional_global_components(graph):
    """Variant 'Professional' must have correct components."""
    variant = graph.get_variant("professional_global")
    assert variant is not None, "Variant professional_global must exist"
    comp_ids = sorted(c["component_id"] for c in variant.components)
    assert comp_ids == ['api_gateway', 'auth_engine', 'billing_core', 'notification_service', 'pricing_engine', 'report_generator', 'search_service', 'workflow_engine']


# Variant Starter EU must contain its assigned components
# Grounding: Variant 'starter_eu' includes: api_gateway, auth_engine, billing_core, notification_service, search_service
def test_variant_starter_eu_components(graph):
    """Variant 'Starter EU' must have correct components."""
    variant = graph.get_variant("starter_eu")
    assert variant is not None, "Variant starter_eu must exist"
    comp_ids = sorted(c["component_id"] for c in variant.components)
    assert comp_ids == ['api_gateway', 'auth_engine', 'billing_core', 'notification_service', 'search_service']


# Variant Starter must contain its assigned components
# Grounding: Variant 'starter_global' includes: api_gateway, auth_engine, billing_core, notification_service, search_service
def test_variant_starter_global_components(graph):
    """Variant 'Starter' must have correct components."""
    variant = graph.get_variant("starter_global")
    assert variant is not None, "Variant starter_global must exist"
    comp_ids = sorted(c["component_id"] for c in variant.components)
    assert comp_ids == ['api_gateway', 'auth_engine', 'billing_core', 'notification_service', 'search_service']


# All shared modules must be correctly identified
# Grounding: Graph has 20 shared modules
def test_shared_modules_detected(graph):
    """Shared modules must match the curated graph."""
    shared = graph.get_shared_modules()
    assert sorted(shared.keys()) == ['access_control', 'cache_layer', 'config_loader', 'crypto_utils', 'currency_utils', 'db_connector', 'event_bus', 'file_storage', 'i18n_utils', 'job_scheduler', 'key_rotation', 'metrics_collector', 'query_builder', 'rate_limiter', 'retry_handler', 'schema_validator', 'session_store', 'tax_calculator', 'template_engine', 'websocket_protocol']


# Module access_control must be used by 3 components
# Grounding: Module 'access_control' is shared by: api_gateway, auth_engine, workflow_engine
def test_shared_module_access_control_users(graph):
    """Module 'access_control' must connect to known components."""
    components = sorted(graph.get_module_components("access_control"))
    assert components == ['api_gateway', 'auth_engine', 'workflow_engine']


# Module cache_layer must be used by 3 components
# Grounding: Module 'cache_layer' is shared by: api_gateway, billing_core, search_service
def test_shared_module_cache_layer_users(graph):
    """Module 'cache_layer' must connect to known components."""
    components = sorted(graph.get_module_components("cache_layer"))
    assert components == ['api_gateway', 'billing_core', 'search_service']


# Module config_loader must be used by 3 components
# Grounding: Module 'config_loader' is shared by: api_gateway, billing_core, encryption_service
def test_shared_module_config_loader_users(graph):
    """Module 'config_loader' must connect to known components."""
    components = sorted(graph.get_module_components("config_loader"))
    assert components == ['api_gateway', 'billing_core', 'encryption_service']


# Module crypto_utils must be used by 2 components
# Grounding: Module 'crypto_utils' is shared by: auth_engine, encryption_service
def test_shared_module_crypto_utils_users(graph):
    """Module 'crypto_utils' must connect to known components."""
    components = sorted(graph.get_module_components("crypto_utils"))
    assert components == ['auth_engine', 'encryption_service']


# Module currency_utils must be used by 3 components
# Grounding: Module 'currency_utils' is shared by: billing_core, pricing_engine, report_generator
def test_shared_module_currency_utils_users(graph):
    """Module 'currency_utils' must connect to known components."""
    components = sorted(graph.get_module_components("currency_utils"))
    assert components == ['billing_core', 'pricing_engine', 'report_generator']


# Module db_connector must be used by 4 components
# Grounding: Module 'db_connector' is shared by: audit_logger, billing_core, report_generator, search_service
def test_shared_module_db_connector_users(graph):
    """Module 'db_connector' must connect to known components."""
    components = sorted(graph.get_module_components("db_connector"))
    assert components == ['audit_logger', 'billing_core', 'report_generator', 'search_service']


# Module event_bus must be used by 4 components
# Grounding: Module 'event_bus' is shared by: audit_logger, auth_engine, notification_service, workflow_engine
def test_shared_module_event_bus_users(graph):
    """Module 'event_bus' must connect to known components."""
    components = sorted(graph.get_module_components("event_bus"))
    assert components == ['audit_logger', 'auth_engine', 'notification_service', 'workflow_engine']


# Module file_storage must be used by 3 components
# Grounding: Module 'file_storage' is shared by: data_exporter, notification_service, report_generator
def test_shared_module_file_storage_users(graph):
    """Module 'file_storage' must connect to known components."""
    components = sorted(graph.get_module_components("file_storage"))
    assert components == ['data_exporter', 'notification_service', 'report_generator']


# Module i18n_utils must be used by 3 components
# Grounding: Module 'i18n_utils' is shared by: notification_service, report_generator, search_service
def test_shared_module_i18n_utils_users(graph):
    """Module 'i18n_utils' must connect to known components."""
    components = sorted(graph.get_module_components("i18n_utils"))
    assert components == ['notification_service', 'report_generator', 'search_service']


# Module job_scheduler must be used by 3 components
# Grounding: Module 'job_scheduler' is shared by: data_exporter, report_generator, workflow_engine
def test_shared_module_job_scheduler_users(graph):
    """Module 'job_scheduler' must connect to known components."""
    components = sorted(graph.get_module_components("job_scheduler"))
    assert components == ['data_exporter', 'report_generator', 'workflow_engine']


# Module key_rotation must be used by 2 components
# Grounding: Module 'key_rotation' is shared by: data_exporter, encryption_service
def test_shared_module_key_rotation_users(graph):
    """Module 'key_rotation' must connect to known components."""
    components = sorted(graph.get_module_components("key_rotation"))
    assert components == ['data_exporter', 'encryption_service']


# Module metrics_collector must be used by 4 components
# Grounding: Module 'metrics_collector' is shared by: api_gateway, billing_core, search_service, websocket_gateway
def test_shared_module_metrics_collector_users(graph):
    """Module 'metrics_collector' must connect to known components."""
    components = sorted(graph.get_module_components("metrics_collector"))
    assert components == ['api_gateway', 'billing_core', 'search_service', 'websocket_gateway']


# Module query_builder must be used by 3 components
# Grounding: Module 'query_builder' is shared by: audit_logger, report_generator, search_service
def test_shared_module_query_builder_users(graph):
    """Module 'query_builder' must connect to known components."""
    components = sorted(graph.get_module_components("query_builder"))
    assert components == ['audit_logger', 'report_generator', 'search_service']


# Module rate_limiter must be used by 3 components
# Grounding: Module 'rate_limiter' is shared by: api_gateway, pricing_engine, search_service
def test_shared_module_rate_limiter_users(graph):
    """Module 'rate_limiter' must connect to known components."""
    components = sorted(graph.get_module_components("rate_limiter"))
    assert components == ['api_gateway', 'pricing_engine', 'search_service']


# Module retry_handler must be used by 3 components
# Grounding: Module 'retry_handler' is shared by: data_exporter, notification_service, websocket_gateway
def test_shared_module_retry_handler_users(graph):
    """Module 'retry_handler' must connect to known components."""
    components = sorted(graph.get_module_components("retry_handler"))
    assert components == ['data_exporter', 'notification_service', 'websocket_gateway']


# Module schema_validator must be used by 3 components
# Grounding: Module 'schema_validator' is shared by: api_gateway, data_exporter, workflow_engine
def test_shared_module_schema_validator_users(graph):
    """Module 'schema_validator' must connect to known components."""
    components = sorted(graph.get_module_components("schema_validator"))
    assert components == ['api_gateway', 'data_exporter', 'workflow_engine']


# Module session_store must be used by 2 components
# Grounding: Module 'session_store' is shared by: auth_engine, websocket_gateway
def test_shared_module_session_store_users(graph):
    """Module 'session_store' must connect to known components."""
    components = sorted(graph.get_module_components("session_store"))
    assert components == ['auth_engine', 'websocket_gateway']


# Module tax_calculator must be used by 2 components
# Grounding: Module 'tax_calculator' is shared by: billing_core, pricing_engine
def test_shared_module_tax_calculator_users(graph):
    """Module 'tax_calculator' must connect to known components."""
    components = sorted(graph.get_module_components("tax_calculator"))
    assert components == ['billing_core', 'pricing_engine']


# Module template_engine must be used by 2 components
# Grounding: Module 'template_engine' is shared by: notification_service, report_generator
def test_shared_module_template_engine_users(graph):
    """Module 'template_engine' must connect to known components."""
    components = sorted(graph.get_module_components("template_engine"))
    assert components == ['notification_service', 'report_generator']


# Module websocket_protocol must be used by 2 components
# Grounding: Module 'websocket_protocol' is shared by: notification_service, websocket_gateway
def test_shared_module_websocket_protocol_users(graph):
    """Module 'websocket_protocol' must connect to known components."""
    components = sorted(graph.get_module_components("websocket_protocol"))
    assert components == ['notification_service', 'websocket_gateway']


# BFS from api_gateway must terminate (cycle safety)
# Grounding: Traversal from api_gateway with max_depth=5
def test_traversal_terminates_api_gateway(graph):
    """BFS from api_gateway must terminate within max_depth."""
    traverser = ImpactTraverser(graph, max_depth=5)
    result = traverser.traverse(["api_gateway"])
    # If we reach here, traversal terminated (no infinite loop)
    assert result is not None
    # All impacts must be within max_depth
    for imp in result.direct_impacts.values():
        assert imp.depth <= 5
    for imp in result.indirect_impacts.values():
        assert imp.depth <= 5


# BFS from audit_logger must terminate (cycle safety)
# Grounding: Traversal from audit_logger with max_depth=5
def test_traversal_terminates_audit_logger(graph):
    """BFS from audit_logger must terminate within max_depth."""
    traverser = ImpactTraverser(graph, max_depth=5)
    result = traverser.traverse(["audit_logger"])
    # If we reach here, traversal terminated (no infinite loop)
    assert result is not None
    # All impacts must be within max_depth
    for imp in result.direct_impacts.values():
        assert imp.depth <= 5
    for imp in result.indirect_impacts.values():
        assert imp.depth <= 5


# BFS from auth_engine must terminate (cycle safety)
# Grounding: Traversal from auth_engine with max_depth=5
def test_traversal_terminates_auth_engine(graph):
    """BFS from auth_engine must terminate within max_depth."""
    traverser = ImpactTraverser(graph, max_depth=5)
    result = traverser.traverse(["auth_engine"])
    # If we reach here, traversal terminated (no infinite loop)
    assert result is not None
    # All impacts must be within max_depth
    for imp in result.direct_impacts.values():
        assert imp.depth <= 5
    for imp in result.indirect_impacts.values():
        assert imp.depth <= 5


# Graph must maintain bipartite structure
# Grounding: Edges only connect component nodes to module nodes
def test_bipartite_structure(graph):
    """Edges must only cross node types (component <-> module)."""
    for u, v in graph.graph.edges():
        u_type = graph.graph.nodes[u].get("node_type")
        v_type = graph.graph.nodes[v].get("node_type")
        assert u_type != v_type, (
            f"Edge {u} -> {v} connects same node types ({u_type})"
        )


# All edges must have coupling and usage metadata
# Grounding: Graph has 57 edges with metadata
def test_edge_metadata_present(graph):
    """Every edge must carry coupling and usage metadata."""
    for u, v, data in graph.graph.edges(data=True):
        assert "coupling" in data, (
            f"Edge {u} -> {v} missing coupling metadata"
        )
        assert data["coupling"] in ("tight", "loose", "optional"), (
            f"Edge {u} -> {v} has invalid coupling: {data['coupling']}"
        )

