"""Dynamic test generator — creates pytest cases grounded in the actual graph.

Generates valid test cases that validate:
  1. Direct impact paths (depth-1 connections via shared modules)
  2. Indirect impact chains (multi-hop paths through the graph)
  3. Variant coverage (components correctly assigned to variants)
  4. Semantic embedding consistency (components are embedded and retrievable)
  5. Cycle detection (known cycles are handled correctly)

All generated tests are strictly grounded in the bipartite graph and vector
store — no hallucinated components or fabricated relationships.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from src.graph.builder import DependencyGraph
from src.graph.traverser import ImpactTraverser

logger = logging.getLogger(__name__)


@dataclass
class GeneratedTest:
    """A single auto-generated test case."""

    name: str
    description: str
    category: str  # "direct_impact", "indirect_impact", "variant", "cycle", "embedding"
    test_code: str
    grounding_evidence: str  # What graph fact this test validates


@dataclass
class TestSuite:
    """Collection of generated tests."""

    tests: list[GeneratedTest] = field(default_factory=list)
    graph_summary: dict[str, Any] = field(default_factory=dict)

    def to_pytest_file(self) -> str:
        """Render all tests as a valid pytest file."""
        lines = [
            '"""Auto-generated impact validation tests.',
            '',
            'Generated by Impact Radar V2 DynamicTestGenerator.',
            'These tests validate structural relationships in the curated dependency graph.',
            'Every assertion is grounded in the bipartite graph — no hallucinated data.',
            '"""',
            '',
            'import pytest',
            'from pathlib import Path',
            '',
            'from src.graph.builder import DependencyGraph',
            'from src.graph.traverser import ImpactTraverser',
            '',
            '',
            'DATA_DIR = Path(__file__).parent.parent / "data"',
            'COMPONENTS_DIR = DATA_DIR / "components"',
            'VARIANTS_DIR = DATA_DIR / "variants"',
            '',
            '',
            '@pytest.fixture',
            'def graph() -> DependencyGraph:',
            '    """Load the curated dependency graph."""',
            '    return DependencyGraph(COMPONENTS_DIR, VARIANTS_DIR)',
            '',
            '',
            '@pytest.fixture',
            'def traverser(graph) -> ImpactTraverser:',
            '    """Create a traverser with default settings."""',
            '    return ImpactTraverser(graph)',
            '',
            '',
        ]

        for test in self.tests:
            lines.append(f'# {test.description}')
            lines.append(f'# Grounding: {test.grounding_evidence}')
            lines.append(test.test_code)
            lines.append('')
            lines.append('')

        return '\n'.join(lines)

    @property
    def summary(self) -> dict[str, Any]:
        categories: dict[str, int] = {}
        for t in self.tests:
            categories[t.category] = categories.get(t.category, 0) + 1
        return {
            "total_tests": len(self.tests),
            "categories": categories,
            "graph_summary": self.graph_summary,
        }


class DynamicTestGenerator:
    """Generates pytest test cases grounded in the actual dependency graph.

    Every generated test asserts facts that are verifiably true in the
    bipartite graph. The generator never fabricates component names,
    module names, or relationships — it reads them from the graph.
    """

    def __init__(self, graph: DependencyGraph) -> None:
        self._graph = graph

    def generate(self) -> TestSuite:
        """Generate a complete test suite from the current graph."""
        suite = TestSuite(graph_summary=self._graph.summary())

        suite.tests.extend(self._generate_component_existence_tests())
        suite.tests.extend(self._generate_direct_impact_tests())
        suite.tests.extend(self._generate_indirect_impact_tests())
        suite.tests.extend(self._generate_variant_coverage_tests())
        suite.tests.extend(self._generate_shared_module_tests())
        suite.tests.extend(self._generate_cycle_safety_tests())
        suite.tests.extend(self._generate_graph_structure_tests())

        logger.info("Generated %d tests: %s", len(suite.tests), suite.summary)
        return suite

    def _generate_component_existence_tests(self) -> list[GeneratedTest]:
        """Generate tests verifying all components exist in the graph."""
        tests: list[GeneratedTest] = []
        components = self._graph.get_components()

        if not components:
            return tests

        comp_ids = sorted(components.keys())
        comp_ids_repr = repr(comp_ids)

        tests.append(GeneratedTest(
            name="test_all_components_present",
            description="Verify all expected components exist in the graph",
            category="structure",
            grounding_evidence=f"Graph contains {len(comp_ids)} components",
            test_code=(
                f'def test_all_components_present(graph):\n'
                f'    """All curated components must be present in the loaded graph."""\n'
                f'    expected = {comp_ids_repr}\n'
                f'    actual = sorted(graph.get_components().keys())\n'
                f'    assert actual == expected'
            ),
        ))

        tests.append(GeneratedTest(
            name="test_component_count",
            description=f"Verify graph has exactly {len(comp_ids)} components",
            category="structure",
            grounding_evidence=f"Graph summary shows {len(comp_ids)} components",
            test_code=(
                f'def test_component_count(graph):\n'
                f'    """Component count must match the curated graph."""\n'
                f'    assert graph.summary()["component_count"] == {len(comp_ids)}'
            ),
        ))

        return tests

    def _generate_direct_impact_tests(self) -> list[GeneratedTest]:
        """Generate tests for direct (depth-1) impact relationships."""
        tests: list[GeneratedTest] = []
        shared_modules = self._graph.get_shared_modules()

        for module_id, component_ids in sorted(shared_modules.items()):
            if len(component_ids) < 2:
                continue

            # Test: changing component_ids[0] should directly impact others
            source = component_ids[0]
            expected_direct = [c for c in component_ids if c != source]

            if not expected_direct:
                continue

            test_name = f"test_direct_impact_via_{module_id}"
            expected_repr = repr(sorted(expected_direct))

            tests.append(GeneratedTest(
                name=test_name,
                description=f"Changing {source} should directly impact peers via {module_id}",
                category="direct_impact",
                grounding_evidence=(
                    f"Module '{module_id}' is shared by: {', '.join(component_ids)}"
                ),
                test_code=(
                    f'def {test_name}(graph, traverser):\n'
                    f'    """Components sharing \'{module_id}\' must appear as direct impacts."""\n'
                    f'    result = traverser.traverse(["{source}"])\n'
                    f'    direct_ids = sorted(result.direct_impacts.keys())\n'
                    f'    expected = {expected_repr}\n'
                    f'    for comp_id in expected:\n'
                    f'        assert comp_id in direct_ids, (\n'
                    f'            f"{{comp_id}} should be a direct impact of {source} via {module_id}"\n'
                    f'        )'
                ),
            ))

            # Limit to avoid too many tests
            if len(tests) >= 15:
                break

        return tests

    def _generate_indirect_impact_tests(self) -> list[GeneratedTest]:
        """Generate tests for indirect (depth 2+) impact chains."""
        tests: list[GeneratedTest] = []
        components = list(self._graph.get_components().keys())

        if len(components) < 3:
            return tests

        # Find indirect impacts by traversing from a few components
        traverser = ImpactTraverser(self._graph, max_depth=3)

        for source in components[:5]:
            result = traverser.traverse([source])

            if not result.indirect_impacts:
                continue

            # Pick the first indirect impact
            indirect_id = next(iter(result.indirect_impacts.keys()))
            indirect = result.indirect_impacts[indirect_id]
            depth = indirect.depth

            test_name = f"test_indirect_impact_{source}_to_{indirect_id}"

            tests.append(GeneratedTest(
                name=test_name,
                description=(
                    f"{source} indirectly impacts {indirect_id} at depth {depth}"
                ),
                category="indirect_impact",
                grounding_evidence=(
                    f"BFS traversal from {source} reaches {indirect_id} at depth {depth}"
                ),
                test_code=(
                    f'def {test_name}(graph, traverser):\n'
                    f'    """Traversal from {source} must reach {indirect_id} indirectly."""\n'
                    f'    result = traverser.traverse(["{source}"])\n'
                    f'    all_affected = result.all_affected_components\n'
                    f'    assert "{indirect_id}" in all_affected, (\n'
                    f'        "{indirect_id} should be affected by changes to {source}"\n'
                    f'    )\n'
                    f'    # Must be indirect (depth > 1), not direct\n'
                    f'    assert "{indirect_id}" in result.indirect_impacts'
                ),
            ))

            if len(tests) >= 5:
                break

        return tests

    def _generate_variant_coverage_tests(self) -> list[GeneratedTest]:
        """Generate tests verifying variant-component assignments."""
        tests: list[GeneratedTest] = []
        variants = self._graph.get_variants()

        if not variants:
            return tests

        for variant_id, variant in sorted(variants.items()):
            comp_ids = sorted(c["component_id"] for c in variant.components)
            if not comp_ids:
                continue

            test_name = f"test_variant_{variant_id}_components"
            comp_ids_repr = repr(comp_ids)

            tests.append(GeneratedTest(
                name=test_name,
                description=f"Variant {variant.name} must contain its assigned components",
                category="variant",
                grounding_evidence=(
                    f"Variant '{variant_id}' includes: {', '.join(comp_ids)}"
                ),
                test_code=(
                    f'def {test_name}(graph):\n'
                    f'    """Variant \'{variant.name}\' must have correct components."""\n'
                    f'    variant = graph.get_variant("{variant_id}")\n'
                    f'    assert variant is not None, "Variant {variant_id} must exist"\n'
                    f'    comp_ids = sorted(c["component_id"] for c in variant.components)\n'
                    f'    assert comp_ids == {comp_ids_repr}'
                ),
            ))

        return tests

    def _generate_shared_module_tests(self) -> list[GeneratedTest]:
        """Generate tests for shared module detection."""
        tests: list[GeneratedTest] = []
        shared = self._graph.get_shared_modules()

        if not shared:
            return tests

        shared_ids = sorted(shared.keys())
        shared_ids_repr = repr(shared_ids)

        tests.append(GeneratedTest(
            name="test_shared_modules_detected",
            description="All shared modules must be correctly identified",
            category="structure",
            grounding_evidence=f"Graph has {len(shared_ids)} shared modules",
            test_code=(
                f'def test_shared_modules_detected(graph):\n'
                f'    """Shared modules must match the curated graph."""\n'
                f'    shared = graph.get_shared_modules()\n'
                f'    assert sorted(shared.keys()) == {shared_ids_repr}'
            ),
        ))

        # Test individual shared module component counts
        for mod_id, comp_ids in sorted(shared.items()):
            test_name = f"test_shared_module_{mod_id}_users"
            tests.append(GeneratedTest(
                name=test_name,
                description=f"Module {mod_id} must be used by {len(comp_ids)} components",
                category="structure",
                grounding_evidence=(
                    f"Module '{mod_id}' is shared by: {', '.join(comp_ids)}"
                ),
                test_code=(
                    f'def {test_name}(graph):\n'
                    f'    """Module \'{mod_id}\' must connect to known components."""\n'
                    f'    components = sorted(graph.get_module_components("{mod_id}"))\n'
                    f'    assert components == {repr(sorted(comp_ids))}'
                ),
            ))

        return tests

    def _generate_cycle_safety_tests(self) -> list[GeneratedTest]:
        """Generate tests ensuring BFS handles cycles without infinite loops."""
        tests: list[GeneratedTest] = []
        components = list(self._graph.get_components().keys())

        if len(components) < 2:
            return tests

        # Test that traversal from any component terminates
        for source in components[:3]:
            test_name = f"test_traversal_terminates_{source}"
            tests.append(GeneratedTest(
                name=test_name,
                description=f"BFS from {source} must terminate (cycle safety)",
                category="cycle",
                grounding_evidence=f"Traversal from {source} with max_depth=5",
                test_code=(
                    f'def {test_name}(graph):\n'
                    f'    """BFS from {source} must terminate within max_depth."""\n'
                    f'    traverser = ImpactTraverser(graph, max_depth=5)\n'
                    f'    result = traverser.traverse(["{source}"])\n'
                    f'    # If we reach here, traversal terminated (no infinite loop)\n'
                    f'    assert result is not None\n'
                    f'    # All impacts must be within max_depth\n'
                    f'    for imp in result.direct_impacts.values():\n'
                    f'        assert imp.depth <= 5\n'
                    f'    for imp in result.indirect_impacts.values():\n'
                    f'        assert imp.depth <= 5'
                ),
            ))

        return tests

    def _generate_graph_structure_tests(self) -> list[GeneratedTest]:
        """Generate tests validating bipartite graph structure."""
        tests: list[GeneratedTest] = []
        summary = self._graph.summary()

        tests.append(GeneratedTest(
            name="test_bipartite_structure",
            description="Graph must maintain bipartite structure",
            category="structure",
            grounding_evidence="Edges only connect component nodes to module nodes",
            test_code=(
                'def test_bipartite_structure(graph):\n'
                '    """Edges must only cross node types (component <-> module)."""\n'
                '    for u, v in graph.graph.edges():\n'
                '        u_type = graph.graph.nodes[u].get("node_type")\n'
                '        v_type = graph.graph.nodes[v].get("node_type")\n'
                '        assert u_type != v_type, (\n'
                '            f"Edge {u} -> {v} connects same node types ({u_type})"\n'
                '        )'
            ),
        ))

        tests.append(GeneratedTest(
            name="test_edge_metadata_present",
            description="All edges must have coupling and usage metadata",
            category="structure",
            grounding_evidence=f"Graph has {summary['edge_count']} edges with metadata",
            test_code=(
                'def test_edge_metadata_present(graph):\n'
                '    """Every edge must carry coupling and usage metadata."""\n'
                '    for u, v, data in graph.graph.edges(data=True):\n'
                '        assert "coupling" in data, (\n'
                '            f"Edge {u} -> {v} missing coupling metadata"\n'
                '        )\n'
                '        assert data["coupling"] in ("tight", "loose", "optional"), (\n'
                '            f"Edge {u} -> {v} has invalid coupling: {data[\'coupling\']}"\n'
                '        )'
            ),
        ))

        return tests

    def write_test_file(
        self,
        output_path: str | Path | None = None,
    ) -> Path:
        """Generate tests and write them to a file."""
        suite = self.generate()
        path = Path(output_path) if output_path else Path("tests/test_generated_impacts.py")
        path.parent.mkdir(parents=True, exist_ok=True)

        content = suite.to_pytest_file()
        path.write_text(content)

        logger.info("Wrote %d tests to %s", len(suite.tests), path)
        return path
